### ISSUE TITLE
Clarification required in the path and query parameter of the callback RequestForProvidingInventoryDataOfDeviceCausesFilteredRequestToMwdi 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/NetworkDataLakeProxy#26]
In a high level , for the RequestForProvidingInventoryDataOfDeviceCausesFilteredRequestToMwdi , could understand from the specification that NDLP --> will communication with MWDI to get the ControlConstruct. 
As per MWDI , "mount-name" is a path parameter to retrieve the ControlConstruct.
But , in the described callback , there is no path/query parameters defined.
For example , 
to get the ControlConstruct , "mount-name" will be a path parameter
```
- name: mount-name
                  in: path
                  required: true
                  schema:
                    type: string
                    example: '222250001'
                  description: >
                    'The mount-name of the device that is addressed by this callback
                    from {$request.body#mount-name}'
```
as per the profilesInstances.yaml , the following text shall be defined as the query parameter
```
'equipment-augment-1-0:control-construct-pac;top-level-equipment;equipment(uuid;operational-state;connector(local-id;equipment-augment-1-0:connector-pac(connector-kind;outside-label;sequence-id));contained-holder(occupying-fru;local-id;equipment-augment-1-0:holder-pac(vendor-label;outside-label;sequence-id));expected-equipment(structure(category);manufactured-thing(manufacturer-properties(manufacturer-name);equipment-type(part-type-identifier;version));local-id;operational-state);actual-equipment(structure(category);physical-properties(temperature);manufactured-thing(manufacturer-properties(manufacturer-name);equipment-type(part-type-identifier;version);equipment-instance(manufacture-date;serial-number));operational-state));firmware-1-0:firmware-collection;logical-termination-point(uuid;layer-protocol(local-id;layer-protocol-name;air-interface-2-0:air-interface-pac(air-interface-configuration);ethernet-container-2-0:ethernet-container-pac(ethernet-container-configuration);hybrid-mw-structure-2-0:hybrid-mw-structure-pac(hybrid-mw-structure-configuration);ip-interface-1-0:ip-interface-pac(ip-interface-configuration);mac-interface-1-0:mac-interface-pac(mac-interface-configuration);pure-ethernet-structure-2-0:pure-ethernet-structure-pac(pure-ethernet-structure-configuration);tdm-container-2-0:tdm-container-pac(tdm-container-configuration);vlan-interface-1-0:vlan-interface-pac(vlan-interface-configuration);wire-interface-2-0:wire-interface-pac(wire-interface-configuration)));profile-collection;forwarding-domain'
```
